'use client'

import { useState } from 'react'
import { updateCustomer, type OwnerCustomer } from '@/app/actions/customers'

export function CustomerManager({ initialCustomers }: { initialCustomers: OwnerCustomer[] }) {
  const [customers, setCustomers] = useState(initialCustomers)
  const [selected, setSelected] = useState<OwnerCustomer | null>(null)
  const [query, setQuery] = useState('')
  const [pending, setPending] = useState(false)
  const [error, setError] = useState('')
  const filtered = customers.filter((c) => `${c.name} ${c.email}`.toLowerCase().includes(query.toLowerCase()))
  async function save() { if (!selected) return; setPending(true); setError(''); try { await updateCustomer(selected.id, selected); setCustomers((all) => all.map((c) => c.id === selected.id ? selected : c)); setSelected(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save customer.') } finally { setPending(false) } }
  return <main className="mx-auto min-h-screen max-w-5xl bg-paper px-6 py-10 text-ink md:px-10"><div className="flex flex-col justify-between gap-4 border-b border-ink/15 pb-6 md:flex-row md:items-end"><div><p className="font-mono text-[11px] uppercase tracking-[0.2em] text-amber">Owner / customers</p><h1 className="mt-2 font-serif text-4xl">Customer book</h1><p className="mt-2 text-sm text-ink/65">A quiet record of the people who trust your business.</p></div><input aria-label="Search customers" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name or email" className="border border-ink/20 bg-paper px-3 py-3 text-sm outline-none focus:border-amber" /></div><div className="mt-8 divide-y divide-ink/10 border-y border-ink/15">{filtered.map((customer) => <button key={customer.id} onClick={() => setSelected(customer)} className="flex w-full flex-col gap-2 py-5 text-left transition-colors hover:bg-ink/[0.03] md:flex-row md:items-center md:justify-between"><span><span className="block font-serif text-xl">{customer.name}</span><span className="mt-1 block text-sm text-ink/60">{customer.email} · {customer.phone || 'No phone'}</span></span><span className="font-mono text-xs text-ink/50">{customer.lastBookingAt ? new Date(customer.lastBookingAt).toLocaleDateString() : 'No bookings'}</span></button>)}{filtered.length === 0 && <p className="py-12 text-center text-sm text-ink/55">No customers match that search.</p>}</div>{selected && <div role="dialog" aria-modal="true" className="fixed inset-0 z-10 flex items-center justify-center bg-ink/30 p-6"><div className="w-full max-w-lg border border-ink/20 bg-paper p-6"><div className="flex justify-between"><h2 className="font-serif text-2xl">Edit customer</h2><button onClick={() => setSelected(null)} aria-label="Close dialog">Close</button></div><div className="mt-6 space-y-4"><label className="block text-sm">Name<input value={selected.name} onChange={(e) => setSelected({ ...selected, name: e.target.value })} className="mt-2 block w-full border border-ink/20 bg-paper px-3 py-3" /></label><label className="block text-sm">Email<input type="email" value={selected.email} onChange={(e) => setSelected({ ...selected, email: e.target.value })} className="mt-2 block w-full border border-ink/20 bg-paper px-3 py-3" /></label><label className="block text-sm">Notes<textarea value={selected.notes} onChange={(e) => setSelected({ ...selected, notes: e.target.value })} className="mt-2 block min-h-24 w-full border border-ink/20 bg-paper px-3 py-3" /></label>{error && <p role="alert" className="text-sm text-red-900">{error}</p>}<button onClick={save} disabled={pending} className="border border-ink bg-ink px-5 py-3 text-sm text-paper disabled:opacity-50">{pending ? 'Saving…' : 'Save changes'}</button></div></div></div>}</main>
}
